name: Specify a new component ✍️
description: ⚠️ This template is for internal use when a component needs to be specified in Figma
title: "Specification for: "
labels: ["figma", "component", "specification"]
body:

  - type: textarea
    id: link
    attributes:
      label: Related issues or relevant information?

  - type: markdown
    attributes:
      value: |
        Check if any tasks could be removed or if you need to add any new tasks.

  - type: textarea
    id: design
    attributes:
      label: Design tasks
      value: |
        - [ ] Design is fully specified in Figma
          - [ ] Design component with all relevant states
          - [ ] Do a accessibility test of the sketches
          - [ ] Functionality/animation is described and prototyped if relevant    
          - [ ] If there are used any svgs in this component is it available for the developer? [Link]
          - [ ] Link to Figma design: [Link]
          - [ ] Pasted screenshot from Figma below :point_down::skin-tone-2:  

  - type: textarea
    id: development
    attributes:
      label: Development Tasks
      value: |
        - [ ] Implement in Storybook
        - [ ] Make sure all variants/properties is possible to turn on/off
        - [ ] Make sure the component is usable across different breakpoints/screen sizes

  - type: textarea
    id: accessibility
    attributes:
      label: Accessibility tasks
      value: |
        - [ ] WCAG-review

