name: Write guidelines 📋
description: ⚠️ This template is for internal use when a component needs guidelines
title: "Guidelines for: "
labels: ["documentation/guidelines"]
body:

  - type: textarea
    id: guidelines
    attributes: 
      label: Guidelines
      value: |
        - [ ] Guidelines are ready
          - [ ] Write/update guidelines
          - [ ] Do's and don'ts
          - [ ] Examples 

